### ISSUE TITLE
Matvec initialization hanging during -n>=3 execution

### ISSUE THREAD

**Issue by bbulgu** [etascale/benchmarks#1] opened 2022-11-21 09:59 UTC
When running matvec with mpirun -n 3 (or anything higher), the execution gets stuck in the `pragma omp for schedule(static)` loop at line 127. When we comment out line 127, matvec runs fine.

**Comment by lundgren87** [comment] 2022-11-21 12:17
Fixed in 39fb2d2252ef61b3e4805172d33441a1b8d1982e according to your suggestion. This extra level of parallelization in fact broke expected data distribution during initialization and must have been an error in the first place. Please feel free to close this issue if the problem is fixed on your end.

**Closed as completed** 2022-11-21 14:26 UTC
Labels: bug
